### ISSUE TITLE
TODO-LIST

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#50]
- [X] Fix issues that /rocket reload cause.  Fixed: [1 of ?]
- [X] Add compatibility with LPX
- [ ] Improve event system to avoid duplicate events.
- [X] Fix system that detect missing properties on config (not work with primitive types)
- [X] Implement enhancements & suggestions.
- [X] Gas can empty in kits & /item

**Comment by Mikuzzzz** [comment]
LPX? Pleb.
Also, use Microsoft word or a word processor.

**Comment by leonardosnt** [comment]
Something wrong?

Define 'pleb'

**Comment by Mikuzzzz** [comment]
Pleb= Commoner
And IMO i think LPX is bad :p
but anyway

**Comment by leonardosnt** [comment]
But a lot of people are asking for this.

**Comment by Mikuzzzz** [comment]
Yea true.
Also, Is ess reload callable by console?

**Comment by leonardosnt** [comment]
yep

**Comment by leonardosnt** [comment]
Or just ? reload

**Comment by waspkiller** [comment]
/ess command is callable by consle
everything is.

**Comment by Mikuzzzz** [comment]
Alright, Thank You,
As well i have another suggestion,
Maybe make it possible to restrict global chat to one language, like EN
or PT

**Comment by leonardosnt** [comment]
maybe

**Comment by waspkiller** [comment]
i love the checkbox Fix poor language. how to fix poor english? talk to engish people.

**Comment by waspkiller** [comment]
![image](https://cloud.githubusercontent.com/assets/10227506/13029249/98f9820a-d254-11e5-94e0-2320e0adbcd7.png)

**Comment by leonardosnt** [comment]
@waspkiller :+1: :+1: :+1: :+1: :+1:

**Comment by Mikuzzzz** [comment]
@leonardosnt ETA on Fixing Reloading Things? plz

**Comment by leonardosnt** [comment]
@Mikuzzzz what you have against the /shutdown? :laughing:

**Comment by waspkiller** [comment]
Shutdown disconnects players and its inconvenint. Btw Not gunna update at this moment. Ill pick a time and update it.

**Comment by Mikuzzzz** [comment]
@leonardosnt Restarting Servers Annoys players..you know we have about 200 players AVG on 12 servers and It's NOT FUN to get spammed by people saying WHY DID THE SERVER RESTART??? WHY DOES IT KEEP RESTARTING?? Not trying to brag :p

**Comment by waspkiller** [comment]
My steam  blows up when my server is down whacha talkin about.

**Comment by waspkiller** [comment]
Still exists #29

**Comment by waspkiller** [comment]
> Fix my poorly english. - it's hard
english is a complex language

**Comment by leonardosnt** [comment]
i know

**Comment by waspkiller** [comment]
i can always proofread your language and correct where necessary but eh. i got games to play this to watch 
![313b50ed04d4bafe9ec23d1abf889d8e](https://cloud.githubusercontent.com/assets/10227506/13029318/1e285968-d257-11e5-9b30-d29be2ff1ea1.jpg)
d29be2ff1ea1.jpg)

**Comment by Mikuzzzz** [comment]
Nice.. Kinda Getting There i suppose.

**Comment by axiomaticTwist** [comment]
I can proofread and edit your "poorly english". I've usually got nothing better to do and I'm bored out of my mind. Email me at m4th3mat1cal@gmail.com if you want me to help out.

**Comment by leonardosnt** [comment]
@axiomaticTwist Many thanks! But im joking, my english is "poorly" but i will "learn with time". Thanks :D

**Comment by waspkiller** [comment]
can we check that off then?

**Comment by Mikuzzzz** [comment]
@leonardosnt Please release the fix to /rocket reload Or atleast give me a ETA :)

**Comment by axiomaticTwist** [comment]
So, you've added /createkit, but you haven't fixed compatibility issues with LIGHT. I'm not one to criticize, but I would like the high priority things to get fixed first, and your priorities may need to be straightened out. I know you're busy, but I'm just extremely looking forward to using these commands with LIGHT. Can't wait! Keep up the great work!

**Comment by leonardosnt** [comment]
@axiomaticTwist Im having issues with lpx, i will add soon.
